CPPSDK: handle patternProperties
rdkcentral/firebolt-openrpc pull request #160
Opened 2023-12-15 16:02 UTC by HaseenaSainul

2023-12-15 16:14 UTC, jlacivita requested changes
Hmm...

It's possible to have a schema with patternProperties AND explicit properties AND additionalProperties definitions...

I can't tell if your code handles this case, but it looks like maybe it does not.

2023-12-15 16:25 UTC, HaseenaSainul commented
> Hmm...
> 
> It's possible to have a schema with patternProperties AND explicit properties AND additionalProperties definitions...
> 
> I can't tell if your code handles this case, but it looks like maybe it does not.

In CPPSDK case for type, patternProperties always treating as string. But during the json parameter generation time we need to know to handle it like a single object instead string. Hence it handling only that part now.

2023-12-19 14:25 UTC, jlacivita commented
Okay, I'll make a test case to ensure we're doing it correctly before we merge to next.

Don't want to hold you up now.

2023-12-19 14:25 UTC, jlacivita approved these changes

2023-12-19 15:20 UTC, merged