Added fix for FIRESDK-20 and FIRESDK-21
rdkcentral/firebolt-openrpc pull request #59
Opened 2022-09-16 11:10 UTC by ChakrabortySubhrajyoti

2022-09-16 11:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/firebolt-openrpc?pullRequest=59) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/firebolt-openrpc?pullRequest=59) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/firebolt-openrpc?pullRequest=59) it.</sub>

2022-09-20 15:22 UTC, jlacivita requested changes

2022-09-20 15:22 UTC, jlacivita commented on util/docs/macros/index.mjs
> +    // added null check to handle the scenario when parameter is optional
The original code is sort of badly designed, and this fix makes it a bit worse.

We should probably refactor `formatParams` to leave out params that are explicitly in the example, and allow for examples to explicitly set a param value to `null` if it wants to.

2022-10-21 06:44 UTC, ChakrabortySubhrajyoti commented
Closing this PR, as the changes for FIRESDK-20 in WIP.

2022-10-21 06:44 UTC, closed without merging